      PROGRAM MAIN
      IMPLICIT NONE 
      CHARACTER(LEN=100) :: FL,FLSPEC
      INTEGER :: NRMX,NREAC,NSTRMX,I,NSPEC
      PARAMETER(NRMX=5000,NSTRMX=500)
      CHARACTER(LEN=NSTRMX) :: CREAC(NRMX),CSPEC(NRMX),REACL(NRMX), &
              PRODL(NRMX)
      INTEGER REAC_SPEC(NRMX,NRMX)
  
      FL='../input_test/reactions.txt'
      FLSPEC='../input_test/species.txt'
      OPEN(UNIT=1,FILE=FL,FORM='FORMATTED',STATUS='OLD')
      OPEN(UNIT=2,FILE=FLSPEC,FORM='FORMATTED',STATUS='OLD')

      CALL PARSE_INDEX_AND_STRING(1,NSTRMX,NRMX,NREAC,CREAC)
      CALL PARSE_INDEX_AND_STRING(2,NSTRMX,NRMX,NSPEC,CSPEC)

      CALL GET_REACTION_SPECIES(NSPEC,NREAC,CSPEC(1:NSPEC), &
              CREAC(1:NREAC),REAC_SPEC(1:NREAC,1:NSPEC))

      CLOSE(1)
      STOP
      END
