      PROGRAM TEST_EXTRACT_NU
      IMPLICIT NONE 
      REAL :: STR2NUM
      LOGICAL :: IS_NUMBER
      CHARACTER(LEN=*) :: STRA
      INTEGER, PARAMETER :: NSPEC=10,NC=100
      INTEGER :: NU(NSPEC,2),I,NA,IEQ
      CHARACTER(LEN=30) :: SPEC(NSPEC),C,CH
      PARAMETER(STRA='   2A+A+10  B+1.5C + 20B+ 23424_K  10R^++U => D + 34A+ 12B + F')
      CHARACTER(LEN=LEN(STRA)) :: STRF,COLMS(NC)
      DOUBLE PRECISION :: NUM


      SPEC(1)='A'
      SPEC(2)='B'
      SPEC(3)='C'
      SPEC(4)='R'
      SPEC(5)='U'
      SPEC(6)='D'
      SPEC(7)='F'

      CALL FORMAT_REACTION(LEN(STRA),STRA,STRF)
      WRITE(*,*) STRF
      IEQ=INDEX(STRF,'=')
      CALL SPLIT_STRING_WITH_SPACES(STRF,NC,COLMS,NA)
      DO I=1,NA
       CALL SPLIT_NUM_AND_CHAR(COLMS(I),30,NUM,CH)
       WRITE(*,*) TRIM(ADJUSTL(COLMS(I))),':',NUM,CH
      ENDDO

      STOP
      END
