      PROGRAM MAIN
      IMPLICIT NONE 
      CHARACTER(LEN=100) :: FL
      INTEGER :: NRMX,NREAC,NSTRMX,I
      PARAMETER(NRMX=5000,NSTRMX=500)
      CHARACTER(LEN=NSTRMX) :: CREAC(NRMX),REACL(NRMX),PRODL(NRMX)
  
      FL='../input_test/reactions.txt'
      OPEN(UNIT=1,FILE=FL,FORM='FORMATTED',STATUS='OLD')

      CALL PARSE_INDEX_AND_STRING(1,NSTRMX,NRMX,NREAC,CREAC)

      CALL SEPARATE_REACTIONS(NREAC,CREAC(1:NREAC), &
              REACL(1:NREAC),PRODL(1:NREAC))
      DO I=1,NREAC
       WRITE(*,*) I,TRIM(ADJUSTL(CREAC(I))),':'
       WRITE(*,*) 'R:',TRIM(ADJUSTL(REACL(I)))
       WRITE(*,*) 'P:',TRIM(ADJUSTL(PRODL(I)))
      ENDDO

      CLOSE(1)
      STOP
      END
