      PROGRAM TEST_GET_REACTION_SPECIES
      IMPLICIT NONE 
      CHARACTER(LEN=100) :: FL,FLSPEC
      INTEGER :: NRMX,NREAC,NSTRMX,I,J,NSPEC
      LOGICAL :: IS_SPEC_IN_REACTION
      PARAMETER(NRMX=5000,NSTRMX=500)
      CHARACTER(LEN=NSTRMX) :: CREAC(NRMX),CSPEC(NRMX),REACL(NRMX), &
              PRODL(NRMX),CREAC_F(NRMX),REAC_SPEC(NRMX,NRMX)
      INTEGER :: NC(NRMX)
   
      FL='../input_test/reactions.txt'
      FLSPEC='../input_test/species.txt'
      OPEN(UNIT=1,FILE=FL,FORM='FORMATTED',STATUS='OLD')
      OPEN(UNIT=2,FILE=FLSPEC,FORM='FORMATTED',STATUS='OLD')

      CALL PARSE_INDEX_AND_STRING(1,NSTRMX,NRMX,NREAC,CREAC)
      CALL PARSE_INDEX_AND_STRING(2,NSTRMX,NRMX,NSPEC,CSPEC)
      CALL GET_FORMATTED_REACTIONS(NREAC,CREAC,CREAC_F)
      CALL GET_REAC_SPEC(' ',NSPEC,NREAC,CREAC_F(1:NREAC), &
                         REAC_SPEC(1:NREAC,1:NSPEC),NC(1:NSPEC))
      
      WRITE(*,*) 'NSPEC=',NSPEC
      WRITE(*,*) 'NREAC=',NREAC
      DO I=1,NREAC
       WRITE(*,'(I4,X,A)') I,TRIM(ADJUSTL(CREAC_F(I)))
       DO J=1,NC(I)
        WRITE(*,'(A)') TRIM(ADJUSTL(REAC_SPEC(I,J)))
       ENDDO
      ENDDO

      CLOSE(1)
      STOP
      END
