      PROGRAM TEST_GET_CHARGED_SPECIES
      IMPLICIT NONE 
      CHARACTER(LEN=100) :: FL,FLSPEC
      INTEGER :: NRMX,NSTRMX,I,J,NSPEC,NN,NC
      LOGICAL :: IS_SPEC_IN_REACTION
      PARAMETER(NRMX=5000,NSTRMX=500)
      CHARACTER(LEN=NSTRMX) :: CSPEC(NRMX),CNEUT(NRMX),CCHAR(NRMX)
   
      FLSPEC='../input_test/species.txt'
      OPEN(UNIT=1,FILE=FLSPEC,FORM='FORMATTED',STATUS='OLD')
      CALL PARSE_INDEX_AND_STRING(1,NSTRMX,NRMX,NSPEC,CSPEC)
      CALL GET_NEUTRAL_SPECIES(NSPEC,CSPEC(1:NSPEC),CNEUT(1:NSPEC),NN)
      CALL GET_CHARGED_SPECIES(NSPEC,CSPEC(1:NSPEC),CCHAR(1:NSPEC),NC)
      
      WRITE(*,*) 'NEUTRAL SPECIES:'
      DO I=1,NN
       WRITE(*,*) I,TRIM(ADJUSTL(CNEUT(I)))
      ENDDO
      WRITE(*,*) 'CHARGED SPECIES:'
      DO I=1,NC
       WRITE(*,*) I,TRIM(ADJUSTL(CCHAR(I)))
      ENDDO


      CLOSE(1)
      STOP
      END
