      PROGRAM TEST_REMOVE_REACTIONS
      IMPLICIT NONE 
      CHARACTER(LEN=100) :: FL
      INTEGER :: NRMX,NREAC,NSTRMX,I,NSPEC,NF
      PARAMETER(NRMX=5000,NSTRMX=500)
      CHARACTER(LEN=NSTRMX) :: CREAC(NRMX),CREAC_F(NRMX)
  
      FL='../input_test/reactions.txt'
      OPEN(UNIT=1,FILE=FL,FORM='FORMATTED',STATUS='OLD')

      CALL PARSE_INDEX_AND_STRING(1,NSTRMX,NRMX,NREAC,CREAC)
      CALL REMOVE_DUPLICATE_REACTIONS(NREAC,CREAC(1:NREAC), &
              CREAC_F(1:NREAC),NF)

      WRITE(*,*) 'NREAC=',NREAC,'NREAC_F=',NF
      DO I=1,NF
       WRITE(*,'(I4,X,A)') I,TRIM(ADJUSTL(CREAC_F(I)))
      ENDDO

      CLOSE(1)
      STOP
      END
