      PROGRAM TEST_GET_REACTION_SPECIES
      USE GLOBAL
      IMPLICIT NONE 
      CHARACTER(LEN=100) :: FL,FLSPEC
      INTEGER :: I,J

      FL='../input_test/reactions.txt'
      FLSPEC='../input_test/species.txt'
      OPEN(UNIT=1,FILE=FL,FORM='FORMATTED',STATUS='OLD')
      OPEN(UNIT=2,FILE=FLSPEC,FORM='FORMATTED',STATUS='OLD')

      CALL READ_INT_AND_STR(FL,REAC,NREAC)
      CALL READ_INT_AND_STR(FLSPEC,SPEC,NSPEC)
      CALL SET_FORMATTED_REACTIONS()
      CALL SET_REACTION_SPECIES()
      !STOP
      WRITE(*,*) 'NSPEC=',NSPEC
      WRITE(*,*) 'NREAC=',NREAC
      DO J=1,NREAC
       WRITE(*,*) TRIM(ADJUSTL(REAC(J)))
       WRITE(*,*) TRIM(ADJUSTL(REACF(J)))
       DO I=1,NSPEC
        IF(IS_SPEC_IN_REAC(I,J)) THEN
         WRITE(*,*) I,TRIM(ADJUSTL(SPEC(I)))
        ENDIF
       ENDDO
      ENDDO

      CLOSE(1)
      STOP
      END
