      PROGRAM TEST_GET_INDEX
      IMPLICIT NONE
      CHARACTER(LEN=*), PARAMETER :: STR='TA+ TXT+ B+ TXT=TXT +TXT +TXT'
      INTEGER, PARAMETER :: N=20
      INTEGER :: IARR(N,2),NA,ND,I
      CHARACTER(LEN=50) :: SLIST(N)

      CALL GET_SUBTEXT_LIST(STR,'TXT',N,SLIST,NA)
      DO I=1,NA
       WRITE(*,*) TRIM(ADJUSTL(SLIST(I)))
      ENDDO
      
      CALL GET_SUBTEXT_DISTINCT_LIST(STR,'TXT',N,SLIST,ND)
      WRITE(*,*) 'NO OF DISTINCT SUBTEXTS:',ND
      DO I=1,ND
       WRITE(*,*) TRIM(ADJUSTL(SLIST(I)))
      ENDDO


      STOP
      END
