      PROGRAM TEST_IS_BOLSIG
      IMPLICIT NONE 
      LOGICAL :: IS_BOLSIG_REACTION
      CHARACTER(LEN=100) :: FL
      INTEGER :: NRMX,NREAC,NSTRMX,I,NSPEC
      PARAMETER(NRMX=5000,NSTRMX=500)
      CHARACTER(LEN=NSTRMX) :: CREAC(NRMX),CSPEC(NRMX),REACL(NRMX), &
              PRODL(NRMX),CREAC_F(NRMX)
      INTEGER REAC_SPEC(NRMX,NRMX)
  
      FL='../input_test/reactions.txt'
      OPEN(UNIT=1,FILE=FL,FORM='FORMATTED',STATUS='OLD')
      CALL PARSE_INDEX_AND_STRING(1,NSTRMX,NRMX,NREAC,CREAC) 
      DO I=1,NREAC
       IF(IS_BOLSIG_REACTION(CREAC(I))) THEN
        WRITE(*,'(I4,X,A)') I,TRIM(ADJUSTL(CREAC(I)))
       ENDIF
      ENDDO

      CLOSE(1)
      STOP
      END
