      PROGRAM TEST_GET_CHARGED_SPECIES
      USE GLOBAL 
      IMPLICIT NONE
      INTEGER :: I,GET_SPECIES_INDEX 
      CHARACTER(LEN=100) :: FL,FLSPEC
   
      FLSPEC='../input_test/species.txt'
      OPEN(UNIT=1,FILE=FLSPEC,FORM='FORMATTED',STATUS='OLD')
      CALL READ_INT_AND_STR(FLSPEC,SPEC,NSPEC)

      DO I=1,NSPEC
       WRITE(*,*) I,GET_SPECIES_INDEX(SPEC(I)),TRIM(ADJUSTL(SPEC(I)))
      ENDDO

      CLOSE(1)
      STOP
      END
