      PROGRAM TEST_IS_CHARGED_SPECIES
      IMPLICIT NONE 
      CHARACTER(LEN=100) :: FLSPEC
      INTEGER :: NRMX,NREAC,NSTRMX,I,NSPEC
      LOGICAL :: IS_CHARGED_SPECIES
      PARAMETER(NRMX=5000,NSTRMX=500)
      CHARACTER(LEN=NSTRMX) :: CSPEC(NRMX)
   
      FLSPEC='../input_test/species.txt'
      OPEN(UNIT=1,FILE=FLSPEC,FORM='FORMATTED',STATUS='OLD')

      CALL PARSE_INDEX_AND_STRING(1,NSTRMX,NRMX,NSPEC,CSPEC)
      DO I=1,NSPEC
       WRITE(*,*) I,TRIM(ADJUSTL(CSPEC(I))),IS_CHARGED_SPECIES(CSPEC(I))
      ENDDO

      CLOSE(1)
      STOP
      END
