      PROGRAM TEST_GET_INDEX
      CHARACTER(LEN=*), PARAMETER :: STR='TA+ TXT+ B+ TXT=TXT +TXT +TXT'
      INTEGER, PARAMETER :: N=20
      INTEGER :: IARR(N,2),NA

      CALL GET_INDEX(STR,'TXT',N,IARR,NA)
      WRITE(*,*) 'STARTING INDICES OF TXT IN STR:'
      DO I=1,NA
       WRITE(*,*) STR(IARR(I,1):IARR(I,2))
      ENDDO

      STOP
      END
