      MODULE GLOBAL
      
      !WORK ARRAYS
      INTEGER, PARAMETER :: NWRKC=5000
      INTEGER, PARAMETER :: NWRKI=5000
      INTEGER, PARAMETER :: NWRKR=5000

      !MAX SPEC AND REAC STRING SIZE
      INTEGER, PARAMETER :: NSTR_SPMX=500
      INTEGER, PARAMETER :: NSTR_REMX=500
      END MODULE GLOBAL
