      MODULE GLOBAL
      
      !WORK ARRAYS
      INTEGER, PARAMETER :: NWRKC=500
      INTEGER, PARAMETER :: NWRKI=500
      INTEGER, PARAMETER :: NWRKR=500

      !MAX SPEC AND REAC STRING SIZE
      INTEGER, PARAMETER :: NSTR_SPMX=500
      INTEGER, PARAMETER :: NSTR_REMX=800

      END MODULE GLOBAL
