      MODULE GLOBAL
      
      INTEGER, PARAMETER :: NWRK=4800
      INTEGER, PARAMETER :: NSMX=100
      CHARACTER(LEN=NSMX) :: REAC(NWRK),SPEC(NWRK),REACF(NWRK)
      INTEGER :: NREAC,NSPEC
      LOGICAL :: IS_SPEC_IN_REAC(NWRK,NWRK)

      CHARACTER(LEN=*), PARAMETER :: BOLSIGID='bolsig'
      CHARACTER(LEN=*), PARAMETER :: NEUTRALID='ANY_NEUTRAL'

      END MODULE GLOBAL
