      MODULE GLOBAL
      
      INTEGER, PARAMETER :: NWRK=5000
      INTEGER, PARAMETER :: NSMX=100
      CHARACTER(LEN=NSMX) :: REAC(NWRK),SPEC(NWRK),REACF(NWRK)
      INTEGER :: NREAC,NSPEC
      LOGICAL :: IS_SPEC_IN_REAC(NWRK,NWRK)

      END MODULE GLOBAL
