      MODULE GLOBAL
      
      INTEGER, PARAMETER :: NREMX=10000,NSPMX=500,NSMX=500, &
       NLINEMX=100000,NSFLMX=1000
      CHARACTER(LEN=*), PARAMETER :: BOLSIGID='bolsig', &
       NEUTRALID='ANY_NEUTRAL',EID='E'
      INTEGER :: NREAC,NSPEC,NSPEC_BOLSIG,NELEM
      CHARACTER(LEN=NSMX) :: ELEM(NSPMX),SPEC(NSPMX),REAC(NREMX), &
       REACF(NREMX),SPEC_BOLSIG(NSPMX),REAC_SPEC(NREMX,NSPMX) 
      LOGICAL :: IS_SPEC_IN_REAC(NSPMX,NREMX),IS_SPEC_NEUTRAL(NSPMX), &
                 IS_BOLSIG_REAC(NREMX)

      END MODULE GLOBAL
