      MODULE GLOBAL
      
      INTEGER, PARAMETER :: NREMX=6000,NSPMX=100
      INTEGER, PARAMETER :: NSMX=500
      INTEGER, PARAMETER :: NSMX_LINE=500
      INTEGER, PARAMETER :: NLINEMX=100000
      INTEGER, PARAMETER :: NSFLMX=1000
      CHARACTER(LEN=*), PARAMETER :: BOLSIGID='bolsig'
      CHARACTER(LEN=*), PARAMETER :: NEUTRALID='ANY_NEUTRAL'
      CHARACTER(LEN=*), PARAMETER :: EID='E'
      INTEGER :: NREAC,NSPEC,NSPEC_BOLSIG,NELEM
      CHARACTER(LEN=NSMX) :: REAC(NREMX),SPEC(NSPMX),REACF(NREMX), &
                             ELEM(NSPMX),SPEC_BOLSIG(NSPMX), &
                             REAC_CONS(NREMX) 
      LOGICAL :: IS_SPEC_IN_REAC(NSPMX,NREMX),IS_SPEC_NEUTRAL(NSPMX), &
                 IS_BOLSIG_REAC(NREMX)

      END MODULE GLOBAL
