      !-----------------------------------------------------------------
      !
      ! AUTHOR: Z. NIKOLAOU
      !
      !-----------------------------------------------------------------
      PROGRAM MAIN_REDCHEM        
      USE GLOBAL
      USE CHEM_PARSE, ONLY : CM_INIT
      IMPLICIT NONE
      INTEGER :: NSPEC_SKEL,NREAC_SKEL,I,J,K,N
      INTEGER, ALLOCATABLE :: TRGD_SET(:,:),TRGD_USET(:,:),SP_USET(:), &
       RE_USET(:),EL_USET(:),SPBOLS_USET(:)
      DOUBLE PRECISION, ALLOCATABLE :: RR(:),OIC(:,:)
      CHARACTER(LEN=NSFLMX) :: FLCASE,BUILD_CASE_DIR
      
      WRITE(*,*) 
      WRITE(*,*) 'MAIN'
      
      CALL READ_CONTROL()           
      
      CALL CM_INIT(INDIR//CHEMFL)
      
      ALLOCATE(TRGD_SET(NTRG,NSPEC))
      ALLOCATE(TRGD_USET(NTRG,NSPEC))
      ALLOCATE(SP_USET(NSPEC))
      ALLOCATE(RE_USET(NREAC))
      ALLOCATE(EL_USET(NELEM))
      ALLOCATE(SPBOLS_USET(NSPEC))
      ALLOCATE(RR(NREAC))
      ALLOCATE(OIC(NTRG,NSPEC))
     
      TRGD_SET(1:NTRG,1:NSPEC)=0
      TRGD_USET(1:NTRG,1:NSPEC)=0
      SP_USET(1:NSPEC)=0
      RE_USET(1:NREAC)=0
      EL_USET(1:NELEM)=1
      SPBOLS_USET(1:NSPEC)=0
      RR(1:NREAC)=ZERO
      OIC(1:NTRG,1:NSPEC)=ZERO
      
      WRITE(*,*) 'GOING THROUGH DATASETS ...'       
      DO N=1,NCASE
       FLCASE=BUILD_CASE_DIR(N)        
       DO I=1,NDATA
        WRITE(*,*) 'CASE ',N,'DATASET ',I
        CALL READ_REACTION_RATES(I,FLCASE,RR)
        CALL DRIVER_DRG(RR,TRGD_SET,OIC)   
        CALL GET_SPECIES_UNION_SET_FOR_TARGET(TRGD_SET,TRGD_USET)
       ENDDO
      ENDDO
      
      CALL GET_SPECIES_SET(TRGD_USET,SP_USET) 
      CALL GET_REACTION_SET(SP_USET,RE_USET)
      CALL GET_BOLSIG_SET(SP_USET,SPBOLS_USET) 
 
      CALL WRITE_REDUCTION_INFO(SP_USET,RE_USET)
                 
      CALL WRITE_CHEM_MECH_FMT_ZDP(EL_USET,SP_USET,SPBOLS_USET,RE_USET)

      WRITE(*,*) 'SKELETAL MECHANISM SIZE:'
      WRITE(*,*) 'NUNION SPEC=',NSPEC_SKEL
      WRITE(*,*) 'NUNION REAC=',NREAC_SKEL
      WRITE(*,*) 
      WRITE(*,*) 'RUN COMPLETED SUCCESSFULLY!'
      
      DEALLOCATE(TRGD_SET)
      DEALLOCATE(TRGD_USET)
      DEALLOCATE(SP_USET)
      DEALLOCATE(RE_USET)
      DEALLOCATE(EL_USET)
      DEALLOCATE(SPBOLS_USET)
      DEALLOCATE(RR)
      DEALLOCATE(OIC)

      STOP
      END
      !-----------------------------------------------------------------
