      !-----------------------------------------------------------------
      !
      ! AUTHOR: Z. NIKOLAOU
      !
      !-----------------------------------------------------------------
      PROGRAM MAIN_REDCHEM        
      USE GLOBAL
      USE CHEM_PARSE, ONLY : CM_INIT
      IMPLICIT NONE
      INTEGER :: NSPEC_SKEL,NREAC_SKEL,I,J,K,N
      INTEGER, ALLOCATABLE :: SET_TRG(:,:),SPSET_TRG(:,:), &
       SPSET_TRGUP(:,:),SPSET_UNION(:),RESET_UNION(:), &
       ELEMSET_UNION(:),SPBOLSET_UNION(:)
      DOUBLE PRECISION, ALLOCATABLE :: RR(:),OIC(:,:)
      CHARACTER(LEN=2) :: JCASE
      CHARACTER(LEN=NSFLMX) :: FLCASE,BUILD_CASE_DIR
      
      WRITE(*,*) 
      WRITE(*,*) 'MAIN'
      
      CALL READ_CONTROL()           
      CALL CM_INIT(INDIR//CHEMFL)
      
      ALLOCATE(RR(NREAC))
      ALLOCATE(SET_TRG(NTRG,NSPEC))
      ALLOCATE(OIC(NTRG,NSPEC))
      ALLOCATE(SPSET_TRGUP(NTRG,NSPEC))
      ALLOCATE(SPSET_UNION(NSPEC))
      ALLOCATE(RESET_UNION(NREAC))
      ALLOCATE(ELEMSET_UNION(NELEM))
      ALLOCATE(SPBOLSET_UNION(NSPEC))
      
      RR(1:NREAC)=ZERO
      OIC(1:NTRG,1:NSPEC)=ZERO
      SET_TRG(1:NTRG,1:NSPEC)=0
      SPSET_TRGUP(1:NTRG,1:NSPEC)=0
      SPSET_UNION(1:NSPEC)=0
      RESET_UNION(1:NREAC)=0
      ELEMSET_UNION(1:NELEM)=1
      SPBOLSET_UNION(1:NSPEC)=0

      WRITE(*,*) 'GOING THROUGH DATASETS ...'       
      DO N=1,NCASE
       FLCASE=BUILD_CASE_DIR(N)        
       DO I=1,NDATA
        WRITE(*,*) 'CASE ',N,'DATASET ',I
        CALL READ_REACTION_RATES(I,FLCASE,RR)
        CALL DRIVER_DRG(INDX_TRG(1:NTRG),ETOL(1:NTRG),RR,SET_TRG,OIC)   
        CALL GET_SPECIES_UNION_SET_FOR_TARGET(SET_TRG,SPSET_TRGUP)
       ENDDO
      ENDDO
      
      WRITE(*,*) 'FINAL TARGET SPECIES SETS:'
      DO I=1,NTRG
       WRITE(*,*) I,TRIM(SPEC(INDX_TRG(I))),SUM(SPSET_TRGUP(I,:))
      ENDDO

      CALL GET_SPECIES_SET(INDX_TRG(1:NTRG),SPSET_TRGUP,SPSET_UNION) 
      CALL GET_REACTION_SET(SPSET_UNION,RESET_UNION)
      CALL GET_BOLSIG_SET(SPSET_UNION,SPEC_BOLSIG(1:NSPEC), &
                          SPBOLSET_UNION) 
 
      WRITE(*,*) 'ELIMINATED SPECIES:'
      DO I=1,NSPEC
       IF(SPSET_UNION(I).EQ.0) THEN
        WRITE(*,*) TRIM(SPEC(I)) 
       ENDIF
      ENDDO
      
      WRITE(*,*) 'SPECIES UNION SET:'
      DO I=1,NSPEC
       IF(SPSET_UNION(I).EQ.1) THEN 
        WRITE(*,*) TRIM(SPEC(I))
       ENDIF
      ENDDO
      
      WRITE(*,*) 'REACTIONS UNION SET:'
      DO I=1,NREAC
       IF(RESET_UNION(I).EQ.1) THEN   
        WRITE(*,*) TRIM(REAC(I))
       ENDIF
      ENDDO
       
      NSPEC_SKEL=SUM(SPSET_UNION)
      NREAC_SKEL=SUM(RESET_UNION)
      IF(NSPEC_SKEL.LE.0.OR.NREAC_SKEL.LE.0) THEN
       WRITE(*,*) 'ERROR: NO SKEL MECH CREATED. TERMINATING ...'
       STOP
      ENDIF
       
      !CALL WRITE_CHEM_MECH_FMT_ZDP(INDX_TRG(1:NTRG), &
      ! ETOL(1:NTRG),ELEM,SPEC,REAC,REAC_CONST,ELEMSET_UNION,SPSET_UNION, &
      ! SPBOLSET_UNION,RESET_UNION,REAC_SEC_DOLLAR_LIST)
      
      CALL WRITE_CHEM_MECH_FMT_ZDP(ELEMSET_UNION,SPSET_UNION, &
       SPBOLSET_UNION,RESET_UNION)


      WRITE(*,*) 'SKELETAL MECHANISM SIZE:'
      WRITE(*,*) 'NUNION SPEC=',NSPEC_SKEL
      WRITE(*,*) 'NUNION REAC=',NREAC_SKEL
      WRITE(*,*) 
      WRITE(*,*) 'RUN COMPLETED SUCCESSFULLY!'
      
      DEALLOCATE(RR)
      DEALLOCATE(SET_TRG)
      DEALLOCATE(OIC)
      DEALLOCATE(SPSET_TRGUP)
      DEALLOCATE(SPSET_UNION)
      DEALLOCATE(RESET_UNION)
      DEALLOCATE(ELEMSET_UNION)
      DEALLOCATE(SPBOLSET_UNION)

      STOP
      END
      !-----------------------------------------------------------------
